excluded:
#  - Pods
  - PrivatePods
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - vertical_whitespace
  - line_length
  - identifier_name
  - xctfail_message
  - weak_delegate
  - file_length
  - unneeded_break_in_switch
  - trailing_newline
  - colon
  - type_name
  - force_cast
  - void_return
  - opening_brace
  - syntactic_sugar
  - control_statement
  - type_body_length
  - return_arrow_whitespace
  - statement_position
  - comma
  - switch_case_alignment
  - unused_optional_binding
  - mark
  - shorthand_operator
  - function_body_length
  - closing_brace
  - closure_parameter_position
  - cyclomatic_complexity
  - unused_closure_parameter
  - compiler_protocol_init
  - empty_parentheses_with_trailing_closure
  - redundant_discardable_let
  - empty_enum_arguments
  - redundant_string_enum_value
  - nesting
  - no_space_in_method_call
  - private_over_fileprivate
  - redundant_optional_initialization
  - legacy_constructor
  - function_parameter_count
analyzer_rules:
  - unused_declaration
