excluded:
  - Pods
  - PrivatePods
disabled_rules:
  - line_length
  - unused_optional_binding
  - compiler_protocol_init
  - empty_parentheses_with_trailing_closure
  - redundant_discardable_let
  - empty_enum_arguments
  - redundant_string_enum_value
  - nesting
  - no_space_in_method_call
  - private_over_fileprivate
  - redundant_optional_initialization
  - legacy_constructor
  - function_parameter_count
analyzer_rules:
  - unused_declaration
